theme = "catppuccin_ortz" # custom catppucin mocha theme

[keys.normal]
# move line up
K = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
# move line down
J = ["extend_to_line_bounds", "delete_selection", "paste_after"]

C-s = ":write"
C-S = ":write!"

C-q = ":quit"
C-Q = ":quit!"

A-h = "jump_view_left"
A-j = "jump_view_down"
A-k = "jump_view_up"
A-l = "jump_view_right"

y = [":clipboard-yank", "yank"]

C-i = "hover"
C-v = ["paste_clipboard_before"]
C-V = ["paste_clipboard_after"]
C-R = ":config-reload"
C-r = "rename_symbol"
C-u = "undo"

H = ":toggle lsp.display-inlay-hints"

"?" = ["move_prev_word_start", "select_mode", "move_next_word_start", "normal_mode", "search_selection"]
esc = ["collapse_selection", "keep_primary_selection"]
"=" = "increment"
"minus" = "decrement"

[keys.select]
C-s = [":write", "normal_mode"]
C-d = "move_next_word_start"

[keys.insert]
C-i = "hover"
C-s = [":write", "normal_mode"]
C-q = ":quit"
C-Q = ":quit!"
C-r = "rename_symbol"
C-R = ":config-reload"
C-v = ["paste_clipboard_before"]
C-V = ["paste_clipboard_after"]

[keys.normal.g]
s = "goto_line_start"
h = "goto_first_nonwhitespace"

[keys.normal.G]
b = "jump_backward"
f = "jump_forward"
h = "jump_view_left"
j = "jump_view_down"
k = "jump_view_up"
l = "jump_view_right"
o = "jumplist_picker"

[editor]
cursorline = true
color-modes = true
true-color = true
mouse = true
rulers = [100]
bufferline = "never"
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
popup-border = "all"
# line-number="relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "↩"
tabpad = "→"

[editor.statusline]
separator = "  "
left = ["mode", "spinner"]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "position", "version-control", "separator"]
mode.normal = " NORMAL"
mode.insert = "󱇨 INSERT"
mode.select = "󰫙 SELECT"
