# Syntax highlighting
# -------------------
"attribute" = "yellow"

"type" = "yellow"
"type.enum.variant" = "teal"

"constructor" = "sapphire"

"constant" = "peach"
"constant.character" = "teal"
"constant.character.escape" = "pink"

"string" = "green"
"string.regexp" = "pink"
"string.special" = "blue"
"string.special.symbol" = "red"

"comment" = { fg = "overlay2", modifiers = ["italic"] }

"variable" = "text"
"variable.parameter" = { fg = "tomate" }
"variable.builtin" = "red"
"variable.other.member" = "teal"

"label" = "sapphire" # used for lifetimes

"punctuation" = "overlay2"
"punctuation.special" = "sky"

# "keyword" = { fg = "mauve", modifiers = ["italic"] }
"keyword" = { fg = "pitaya", modifiers = ["italic"] }

"operator" = "sky"

"function" = "figo"
"function.macro" = "mauve"

"tag" = "mauve"

# "namespace" = { fg = "yellow", modifiers = ["italic"] }
"namespace" = { fg = "banana", modifiers = ["bold"] }

"special" = "blue" # fuzzy highlight

"markup.heading.marker" = { fg = "peach", modifiers = ["bold"] }
"markup.heading.1" = "lavender"
"markup.heading.2" = "mauve"
"markup.heading.3" = "green"
"markup.heading.4" = "yellow"
"markup.heading.5" = "pink"
"markup.heading.6" = "teal"
"markup.list" = "mauve"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "blue", modifiers = ["italic", "underlined"] }
"markup.link.text" = "blue"
"markup.raw" = "flamingo"

"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "blue"

# User Interface
# --------------
"ui.background" = { fg = "text", bg = "crust" }

"ui.linenr" = { fg = "surface1" }
"ui.linenr.selected" = { fg = "lavender" }

"ui.statusline" = { fg = "subtext1", bg = "mantle" }
"ui.statusline.inactive" = { fg = "surface2", bg = "mantle" }
# "ui.statusline.normal" = { fg = "subtext1", bg = "mantle" }
"ui.statusline.normal" = { fg = "base", bg = "figo", modifiers = ["bold"]  }
"ui.statusline.insert" = { fg = "base", bg = "avocado", modifiers = ["bold"]  }
"ui.statusline.select" = { fg = "base", bg = "pitaya", modifiers = ["bold"]  }

"ui.popup" = { fg = "text", bg = "surface0" }
"ui.window" = { fg = "crust" }
"ui.help" = { fg = "overlay2", bg = "surface0" }

"ui.bufferline" = { fg = "subtext0", bg = "mantle", modifiers = ["italic", "dim"] }
"ui.bufferline.active" = { fg = "mauve", bg = "base", modifiers = ["bold"] }
"ui.bufferline.background" = { bg = "crust" }

"ui.text" = "text"
"ui.text.focus" = { fg = "text", bg = "surface0", modifiers = ["bold"] }
"ui.text.inactive" = { fg = "overlay1" }

"ui.virtual" = "overlay0"
"ui.virtual.ruler" = { bg = "surface0" }
"ui.virtual.indent-guide" = "surface0"
"ui.virtual.inlay-hint" = { fg = "surface1" }
"ui.virtual.jump-label" = { fg = "rosewater", modifiers = ["bold"] }

"ui.selection" = { bg = "surface1" }

"ui.cursor" = { fg = "base", bg = "secondary_cursor" }
"ui.cursor.primary" = { fg = "base", bg = "rosewater" }
"ui.cursor.match" = { fg = "peach", modifiers = ["bold"] }

"ui.cursor.primary.normal" = { fg = "base", bg = "lavender" }
"ui.cursor.primary.insert" = { fg = "base", bg = "green" }
"ui.cursor.primary.select" = { fg = "base", bg = "flamingo" }

"ui.cursor.normal" = { fg = "base", bg = "secondary_cursor_normal" }
"ui.cursor.insert" = { fg = "base", bg = "secondary_cursor_insert" }
"ui.cursor.select" = { fg = "base", bg = "secondary_cursor" }

"ui.cursorline.primary" = { bg = "cursorline" }

"ui.highlight" = { bg = "surface1", modifiers = ["bold"] }

"ui.menu" = { fg = "overlay2", bg = "surface0" }
"ui.menu.selected" = { fg = "text", bg = "surface1", modifiers = ["bold"] }

"diagnostic.error" = { bg = "overlay_danger" }
"diagnostic.warning" = { bg = "overlay_warning" }
"diagnostic.info" = { bg = "overlay_info" } 
"diagnostic.hint" = { bg = "overlay_hint" }

error = "red"
warning = "yellow"
info = "sky"
hint = "teal"

[palette]
# catppuccin palette colors
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"

text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"

base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# derived colors by blending existing palette colors
cursorline = "#2a2b3c"
secondary_cursor = "#b5a6a8"
secondary_cursor_normal = "#878ec0"
secondary_cursor_insert = "#7da87e"

# ortz colors
amora    = "#1B2430"
baunilha = "#F9F9F9"
banana   = "#FAF4B7"
avocado  = "#96F7D2"
mirtilo  = "#B5DEFF"
figo     = "#CAB8FF"
pitaya   = "#F5B5FC"
tomate   = "#FCB1B1"
uva      = "#51557E"
pessego  = "#FFBE98"
morango  = "#D80E70"

overlay_danger = "#341b29"
overlay_warning = "#403D2E"
overlay_hint = "#1B3342"
overlay_info = "#1A254D"
